### ISSUE TITLE
Publish 0.8.x releases on Sonatype

### ISSUE THREAD

**Issue by lolgab** [tkqubo/scala-html-to-markdown#9]
The 0.8.x releases are on Github but I can't find them on Sonatype.

**Comment by tkqubo-dotdata** [comment]
I tried sbt release and think it's already uploaded to Sonatype.  But it might take time.  Tomorrow I will check it again.

**Comment by tkqubo-dotdata** [comment]
Sorry, I forgot to actually execute release it in the Sonatype Repository.  Now we can wait for less than an hour or so for the release @lolgab

**Comment by lolgab** [comment]
Thank you for this library :-)

**Comment by tkqubo** [comment]
I believe this issue can be closed.
